\input{"C:/Users/Jake Truscott/Documents/GitHub/jaketruscott.github.io/_scotuswatch/stat_pack_OT23/statpack_style.tex"}


\begin{document}

\begin{tikzpicture}[remember picture, overlay]
  \draw[line width = 4pt] ($(current page.north west) + (0.7in,-0.7in)$) rectangle ($(current page.south east) + (-0.7in,0.7in)$);
\end{tikzpicture}

\thispagestyle{empty}
\begin{center}
  \Huge \textbf{Supreme Court 2023-2024 Term} \\
  \LARGE \textbf{Stat Pack} \\[7mm]
  \includegraphics[width=300px]{Figures/empirical_scotus_logo.png}\\[2mm]
  \textbf{EmpiricalSCOTUS} \\
  \textit{Viewing the Supreme Court in an Entirely New Light} \\[3mm]

  \normalsize
  Compiled by Adam Feldman (J.D., Ph.D.) and Jake S. Truscott (Ph.D.) \\
  \vfill

  \footnotesize
  Version: 0.1 (Released \textcolor{blue}{\textless DATE\textgreater{}}) \\[2mm]

  \normalsize
We give particular thanks to \textcolor{blue}{\textless NAME\textgreater{}} and \textcolor{blue}{\textless NAME\textgreater{}} for their assistance reviewing these materials prior to their public release. For additional data and accompanying analysis, please visit\\ \textcolor{blue}{\href{https://empiricalscotus.com/}{EmpiricalSCOTUS}} or \textcolor{blue}{\href{mailto:adam@feldmannet.com}{Contact Us}}.

\end{center}
\newpage



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Table of Contents
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage
\renewcommand{\contentsname}{\centering\huge\textbf{\underline{Table of Contents}}}

\begin{center}
\tableofcontents
\end{center}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Preface %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage
\setcounter{page}{1}

\section{\underline{Preface}}

\input{"C:/Users/Jake Truscott/Documents/GitHub/jaketruscott.github.io/_scotuswatch/stat_pack_OT23/statpack_sections/preface_statpack.tex"}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Data Disclosure %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage
\section{\underline{Data Disclosure}}

\input{"C:/Users/Jake Truscott/Documents/GitHub/jaketruscott.github.io/_scotuswatch/stat_pack_OT23/statpack_sections/data_disclosure_statpack.tex"}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Introduction %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage
\section{\underline{Introduction}}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Toplines %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage

\input{"C:/Users/Jake Truscott/Documents/GitHub/jaketruscott.github.io/_scotuswatch/stat_pack_OT23/statpack_sections/topline_statistics_statpack.tex"}

\newpage

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Oral Arguments %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Oral Arguments Intro Page
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{center}
    \vspace{5cm}
    {\Huge\textbf{\section{\underline{Oral Arguments}}}} % Large and bold text
    \begin{figure}[h]
        \centering
        \includegraphics[width=0.85\textwidth]{C:/Users/Jake Truscott/Documents/GitHub/jaketruscott.github.io/_scotuswatch/stat_pack_OT23/Figures/hennessey_courtroom_sketch.jpg} \\
        \footnotesize{Photo Credit: Courtroom sketch by Bill Hennessy (PBS NewsHour)} \\
        \vspace{2mm}
        \includegraphics[width=0.85\textwidth]{C:/Users/Jake Truscott/Documents/GitHub/jaketruscott.github.io/_scotuswatch/stat_pack_OT23/Figures/hennessey_courtroom_sketch_2.jpg} \\
        \footnotesize{Photo Credit: Courtroom sketch by Bill Hennessy (CNN)} \\

    \end{figure}
\end{center}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% OA Calendar
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage

\input{"C:/Users/Jake Truscott/Documents/GitHub/jaketruscott.github.io/_scotuswatch/stat_pack_OT23/statpack_sections/oral_argument_calendar_statpack.tex"}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Participation - Totals (Justice)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\subsection{\centering Oral Argument Participation -- Justices}
\begin{figure}[H]
\centering
\caption{Total Word Counts (By Justice - OT2023)}
\vspace{2.5mm}
\includegraphics[width = 0.9\textwidth]{"C:/Users/Jake Truscott/Documents/GitHub/jaketruscott.github.io/images/scotuswatch_tables/OT23 Totals/word_count_plot_OT23.png"} \\
\vspace{2mm}
\footnotesize{Data Source: Compiled from Oyez}
\end{figure}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% OA Justice Word Counts
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\input{"C:/Users/Jake Truscott/Documents/GitHub/jaketruscott.github.io/_scotuswatch/stat_pack_OT23/statpack_sections/oral_argument_word_counts_justices_statpack.tex"}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% OA Attorney Word Counts
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\input{"C:/Users/Jake Truscott/Documents/GitHub/jaketruscott.github.io/_scotuswatch/stat_pack_OT23/statpack_sections/oral_argument_participation_attorneys_statpack.tex"}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% OA Justice Speaking Times
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\input{"C:/Users/Jake Truscott/Documents/GitHub/jaketruscott.github.io/_scotuswatch/stat_pack_OT23/statpack_sections/oral_argument_justice_speaking_times_statpack.tex"}


\newpage



















%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Decisions %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{\underline{Decisions}}


\newpage




\subsection{Frequency in Majority}
\subsection{Decision by Coalition}
\subsection{Voting Alignments}
\subsection{Opinion Authorship}
\subsection{Split Decisions: (6-3) and (5-4)}
\subsection{Unanimity}
\subsection{Turnover Between Arguments Decision}
\subsection{Circuit Scorecard}




























%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Docket %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Docket Intro Page
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\begin{center}
    \vspace{5cm}
    {\Huge\textbf{\section{\underline{Docket}}}} % Large and bold text
    \begin{figure}[h]
        \centering
        \includegraphics[width=0.85\textwidth]{C:/Users/Jake Truscott/Documents/GitHub/jaketruscott.github.io/_scotuswatch/stat_pack_OT23/Figures/docket_filing.jpg} \\
        \footnotesize{Photo Credit: Chris Geidner (Law Dork)} \\
        \vspace{2mm}
        \includegraphics[width=0.85\textwidth]{C:/Users/Jake Truscott/Documents/GitHub/jaketruscott.github.io/_scotuswatch/stat_pack_OT23/Figures/docket_filing_books.jpg} \\
        \footnotesize{Photo Credit: Donna Sokol (Library of Congress Blogs)} \\

    \end{figure}
\end{center}
\newpage

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Filing Trends by Month (OT23)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{figure}[H]
\subsection{\centering Filing Trends -- 2023 Term}
\centering
\caption{Filing Trends by Type (OT2023)}
\includegraphics[width = 0.9\textwidth]{"C:/Users/Jake Truscott/Documents/GitHub/jaketruscott.github.io/_scotuswatch/stat_pack_OT23/Figures/dockets_ot_23.png"} \\
\footnotesize{\emph{Note}: Does not include original jurisdiction filings.} \\
\footnotesize{Data Source: \href{https://www.supremecourt.gov/docket/docket.aspx}{Supreme Court of the United States} (Retrieved using \href{https://jaketruscott.github.io/scotustext/}{\texttt{scotustext R}})}

\end{figure}

\newpage

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Court of Origin
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\input{"C:/Users/Jake Truscott/Documents/GitHub/jaketruscott.github.io/_scotuswatch/stat_pack_OT23/statpack_sections/docket_court_of_origin.tex"}

\newpage

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Emergency Orders
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\subsection{Emergency Orders}




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Final Notes %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{\underline{Final Notes}}




%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% References
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage
\section{\underline{References}}
































\end{document}
